# Python Review

Short review about some core concepts in Python exemplified by objects in the Numpy Library.
Goals: 
- recall basic Python vocab
- practice markdown syntax 

## Libraries and packages

**Library:** is a collection of code that we can use to perform specific tasks in our programs. It can be a single file or multiple files.

**NumPy:**
- core library for numerical computing in Python 
- many of libraaries use NumPy arrays as their building blocks
- computations on NumPy objects are optimized for speed and memory usage 

Let's import NumPy with its **standard abbreviation** `np`:

In [1]:
import numpy as np

(esc + press M twice -> convert code cell to markdown cell)
## Variables 
**variable:** a name we assigned to a particular object in Python

Example:

In [4]:
# Assign a small array to variable a
a = np.array([ [1, 1, 2], [3, 5, 8]])

To view a variable's value from our Jupyter notebook: 

In [5]:
# Run cell with variable name to show value
a

array([[1, 1, 2],
       [3, 5, 8]])

In [6]:
# Use `print` function to print value
print(a)

[[1 1 2]
 [3 5 8]]
